package com.example.TaxiTelegramBot.enums;

public enum TypeOfSpecialMessage {
    USER_REGISTER_LOGIN,
    USER_REGISTER_PASSWORD,
    USER_REGISTER_FIO,
    USER_REGISTER_CITY,

    USER_AUTORIZE,

    DRIVER_REGISTER_LOGIN,

    DRIVER_REGISTER_PASSWORD,

    DRIVER_REGISTER_FIO,

    DRIVER_REGISTER_CITY,

    DRIVER_REGISTER_AUTO_NUMBER,

    DRIVER_REGISTER_DRIVE_EXPIRIENCE,

    DRIVER_REGISTER_AUTO_CLASS,

    DRIVER_REGISTER_AUTO_MARK,

    DRIVER_REGISTER_AUTO_COLOR,

    DRIVER_REGISTER_PHOTO,

    DRIVER_AUTORIZE;
}
